const {
  // Base URL
  REACT_APP_LOCAL_BASE_URL,
  REACT_APP_DEPLOYED_BASE_URL,
  // BASE API URL
  REACT_APP_DEVELOPMENT_API_BASE,
  REACT_APP_PRODUCTION_API_BASE,
  // Firebase Development
  REACT_APP_DEVELOPMENT_FIREBASE_API_KEY,
  REACT_APP_DEVELOPMENT_FIREBASE_AUTH_DOMAIN,
  REACT_APP_DEVELOPMENT_FIREBASE_DATABASE_URL,
  REACT_APP_DEVELOPMENT_FIREBASE_PROJECT_ID,
  REACT_APP_DEVELOPMENT_FIREBASE_STORAGE_BUCKET,
  REACT_APP_DEVELOPMENT_FIREBASE_MESSAGING_SENDER_ID,
  REACT_APP_DEVELOPMENT_FIREBASE_APP_ID,
  REACT_APP_DEVELOPMENT_FIREBASE_MEASUREMENT_ID,
  // Firebase Production
  REACT_APP_PRODUCTION_FIREBASE_API_KEY,
  REACT_APP_PRODUCTION_FIREBASE_AUTH_DOMAIN,
  REACT_APP_PRODUCTION_FIREBASE_DATABASE_URL,
  REACT_APP_PRODUCTION_FIREBASE_PROJECT_ID,
  REACT_APP_PRODUCTION_FIREBASE_STORAGE_BUCKET,
  REACT_APP_PRODUCTION_FIREBASE_MESSAGING_SENDER_ID,
  REACT_APP_PRODUCTION_FIREBASE_APP_ID,
  REACT_APP_PRODUCTION_FIREBASE_MEASUREMENT_ID,
} = process.env;

//
// Firebase
//

const DEVELOPMENT_FB = {
  FIREBASE_API_KEY: REACT_APP_DEVELOPMENT_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: REACT_APP_DEVELOPMENT_FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL: REACT_APP_DEVELOPMENT_FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID: REACT_APP_DEVELOPMENT_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: REACT_APP_DEVELOPMENT_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID:
    REACT_APP_DEVELOPMENT_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: REACT_APP_DEVELOPMENT_FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: REACT_APP_DEVELOPMENT_FIREBASE_MEASUREMENT_ID,
};
const PRODUCTION_FB = {
  FIREBASE_API_KEY: REACT_APP_PRODUCTION_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: REACT_APP_PRODUCTION_FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL: REACT_APP_PRODUCTION_FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID: REACT_APP_PRODUCTION_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: REACT_APP_PRODUCTION_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID:
    REACT_APP_PRODUCTION_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: REACT_APP_PRODUCTION_FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: REACT_APP_PRODUCTION_FIREBASE_MEASUREMENT_ID,
};

//
// Configurations
//
const DEVELOPMENT = {
  dev: true,
  BASE_URL: REACT_APP_LOCAL_BASE_URL,
  API_BASE_URL: REACT_APP_DEVELOPMENT_API_BASE,
  // API_BASE_URL: REACT_APP_PRODUCTION_API_BASE,
  API_DEBUGGING: true,
  FIREBASE_PERFORMANCE: false,
  ...DEVELOPMENT_FB,
};
const PRODUCTION = {
  dev: false,
  BASE_URL: REACT_APP_DEPLOYED_BASE_URL,
  API_BASE_URL: REACT_APP_PRODUCTION_API_BASE,
  API_DEBUGGING: false,
  FIREBASE_PERFORMANCE: true,
  ...PRODUCTION_FB,
};

export const settings = {
  VERSION: '0.1.0',

  // ...DEVELOPMENT,
  // ...PRODUCTION,
  ...(process.env.NODE_ENV === 'development' ? DEVELOPMENT : PRODUCTION),
};
