name: Admin Lint & Test
on:
  pull_request:
    paths:
      - 'admin/**'
      - '.github/workflows/admin**'
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./admin
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn lint --max-warnings=0
      # - run: yarn test
  build_and_deploy:
    runs-on: ubuntu-latest
    if: contains(github.base_ref, 'master')
    needs: lint_and_test
    defaults:
      run:
        working-directory: ./admin
    steps:
      - uses: actions/checkout@v2
      - run: yarn ci && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FAMILY_WEBSITE_PROD }}'
          channelId: live
          projectId: family-website-prod
          target: admin
