name: Admin Lint & Test
on:
  push:
    paths:
      - 'admin/**'
      - '.github/workflows/admin**'
jobs:
  Lint And Test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: cd admin
      - run: yarn install
      - run: yarn lint
      - run: yarn test
