name: Family Jobs
on:
  pull_request:
    paths:
      - 'family/**'
      - '.github/workflows/family**'
  push:
    branches:
      - master
    paths:
      - 'family/**'
      - '.github/workflows/family**'
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./family
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn lint --max-warnings=0
      # - run: yarn test
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [lint_and_test]
    defaults:
      run:
        working-directory: ./family
    env:
      REACT_APP_PRODUCTION_FIREBASE_API_KEY: ${{ secrets.REACT_APP_PRODUCTION_FIREBASE_API_KEY }}
      REACT_APP_PRODUCTION_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_PRODUCTION_FIREBASE_AUTH_DOMAIN }}
      REACT_APP_PRODUCTION_FIREBASE_DATABASE_URL: ${{ secrets.REACT_APP_PRODUCTION_FIREBASE_DATABASE_URL }}
      REACT_APP_PRODUCTION_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_PRODUCTION_FIREBASE_PROJECT_ID }}
      REACT_APP_PRODUCTION_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_PRODUCTION_FIREBASE_STORAGE_BUCKET }}
      REACT_APP_PRODUCTION_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_PRODUCTION_FIREBASE_MESSAGING_SENDER_ID }}
      REACT_APP_PRODUCTION_FIREBASE_APP_ID: ${{ secrets.REACT_APP_PRODUCTION_FIREBASE_APP_ID }}
      REACT_APP_PRODUCTION_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_PRODUCTION_FIREBASE_MEASUREMENT_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FAMILY_WEBSITE_PROD }}'
          channelId: live
          projectId: family-website-prod
          target: family
