name: Family Lint & Test
on:
  push:
    paths:
      - 'family/**'
      - '.github/workflows/family**'
  pull_request:
    paths:
      - 'family/**'
      - '.github/workflows/family**'
jobs:
  Lint_And_Test:
    name: Lint And Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./family
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn lint --max-warnings=0
      # - run: yarn test
